function restaurant1_avg_data = importfileAVG(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  RESTAURANT1_AVG_DATA = IMPORTFILE2(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  RESTAURANT1_AVG_DATA = IMPORTFILE2(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  restaurant1_avg_data = importfileAVG("/Users/gabrielleliebenberg/MATLAB/Projects/untitled/restaurant1_avg_data.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Oct-2022 09:53:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["date", "ItemName", "Quantity", "ProductPrice", "cloud_cover", "sunshine", "global_radiation", "max_temp", "mean_temp", "min_temp", "precipitation", "pressure", "snow_depth", "isPaidTimeOff"];
opts.VariableTypes = ["datetime", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "isPaidTimeOff", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ItemName", "isPaidTimeOff"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM-dd");

% Import the data
restaurant1_avg_data = readtable(filename, opts);

end