function restaurant1_data_1 = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  RESTAURANT1_DATA_1 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RESTAURANT1_DATA_1 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  restaurant1_data_1 = importfile1("/Users/gabrielleliebenberg/MATLAB/Projects/untitled/restaurant1_data.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Oct-2022 18:55:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "OrderNumber", "OrderDate", "ItemName", "Quantity", "ProductPrice", "TotalProducts", "date", "cloud_cover", "sunshine", "global_radiation", "max_temp", "mean_temp", "min_temp", "precipitation", "pressure", "snow_depth", "countryOrRegion", "holidayName", "normalizeHolidayName", "isPaidTimeOff", "countryRegionCode"];
opts.VariableTypes = ["double", "double", "datetime", "categorical", "double", "double", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["countryOrRegion", "holidayName", "normalizeHolidayName", "isPaidTimeOff", "countryRegionCode"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ItemName", "countryOrRegion", "holidayName", "normalizeHolidayName", "isPaidTimeOff", "countryRegionCode"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "OrderDate", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM-dd");

% Import the data
restaurant1_data_1 = readtable(filename, opts);

end